---
# tasks file for roles/apache
- name: Install Apache
  yum: 
    name: httpd
    state: latest

- name: Open service in firewalld
  firewalld:
    service: http
    permanent: yes
    state: enabled
    immediate: yes
  notify: restart firewalld

- name: Copy index
  template: 
    src: index.html.j2
    dest: /var/www/html/index.html
    owner: apache
    group: apache
    mode: '0664'

- name: Restart & enabled service httpd
  service:
    name: httpd
    state: restarted
    enabled: yes

