---
- name: generate host file all
  hosts: all
  become: true

- name: generate host file dev
  hosts: dev
  become: true
  tasks:
    - name: generate
      template: 
        src: hosts.j2
        dest: /etc/myhosts
