---
- name: install apache role
  hosts: webservers
  become: true
  roles:
    - apache

- name: install phpinfo role
  hosts: webservers
  become: true
  roles:
    - phpinfo

- name: install balancer role
  hosts: balancers
  become: true
  roles:
    - balancer