---
- name: Create a web content directory
  hosts: dev
  become: true
  tasks:
    - name: Install Apache
      yum: 
        name: httpd
        state: latest

    - name: Open service in firewalld
      firewalld:
        service: http
        permanent: yes
        state: enabled
        immediate: yes
      notify: restart firewalld

    - name: create group
      group:
        name: webdev
        state: present
        
    - name: create webdev dir
      file:
        path: /webdev
        group: webdev
        mode: '2775'
        state: directory
        setype: httpd_sys_content_t

    - name: create link
      file:
        src: /webdev
        dest: /var/www/html/webdev
        state: link

    - name: Copy index
      copy: 
        content: "Development\n"
        dest: /webdev/index.html
        setype: httpd_sys_content_t

    - name: Restart & enabled service httpd
      service:
        name: httpd
        state: restarted
        enabled: yes

  handlers:
    - name: restart firewalld
      service: name=firewalld state=restarted